# Generated by Django 4.2.9 on 2026-07-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_notification_target_user_usernotification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="notifications/"),
        ),
    ]
