# Generated by Django 4.2.9 on 2026-07-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sponsor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("national_funding", "National Funding Agency"),
                            ("platinum", "Platinum Sponsor"),
                            ("silver", "Silver Sponsor"),
                            ("bronze", "Bronze Sponsor"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="sponsors/logos/"
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("website_url", models.URLField(blank=True, default="")),
                (
                    "contact_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("address", models.CharField(blank=True, default="", max_length=400)),
                ("linkedin_url", models.URLField(blank=True, default="")),
                ("twitter_url", models.URLField(blank=True, default="")),
                ("facebook_url", models.URLField(blank=True, default="")),
                ("instagram_url", models.URLField(blank=True, default="")),
                ("youtube_url", models.URLField(blank=True, default="")),
                (
                    "partnership_details",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Benefits / partnership description shown on detail page.",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers show first within a tier."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Sponsor",
                "verbose_name_plural": "Sponsors",
                "ordering": ["tier", "display_order", "name"],
            },
        ),
    ]
