# Generated by Django 4.2.9 on 2026-08-08 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("speakers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedbackForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Session Feedback", max_length=300)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ScheduleSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "day",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Day 1"), (2, "Day 2"), (3, "Day 3")],
                        db_index=True,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("keynote", "Keynote"),
                            ("technical", "Technical Session"),
                            ("workshop", "Workshop"),
                            ("break", "Break"),
                            ("meal", "Meal"),
                            ("cultural", "Cultural"),
                            ("panel", "Panel Discussion"),
                            ("special", "Special Session"),
                            ("ideathon", "Ideathon"),
                            ("ceremony", "Ceremony"),
                        ],
                        default="technical",
                        max_length=20,
                    ),
                ),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                ("room", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="★ Highlighted session"
                    ),
                ),
                (
                    "is_parallel",
                    models.BooleanField(
                        default=False, help_text="Runs alongside another session"
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("feedback_enabled", models.BooleanField(default=False)),
                (
                    "feedback_auto_open",
                    models.BooleanField(
                        default=True, help_text="Auto-enable at end_datetime"
                    ),
                ),
                (
                    "feedback_manual_open",
                    models.BooleanField(
                        default=False, help_text="Admin manually opened"
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "speaker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions",
                        to="speakers.speaker",
                    ),
                ),
            ],
            options={
                "verbose_name": "Session",
                "ordering": ["day", "display_order", "start_datetime"],
            },
        ),
        migrations.CreateModel(
            name="ScheduleSubSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("start_datetime", models.DateTimeField(blank=True, null=True)),
                ("end_datetime", models.DateTimeField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_sessions",
                        to="schedule.schedulesession",
                    ),
                ),
                (
                    "speaker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sub_sessions",
                        to="speakers.speaker",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "start_datetime"],
            },
        ),
        migrations.CreateModel(
            name="FeedbackResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="schedule.feedbackform",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_responses",
                        to="schedule.schedulesession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
                "unique_together": {("user", "session")},
            },
        ),
        migrations.CreateModel(
            name="FeedbackQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.CharField(max_length=500)),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("rating", "Star Rating (1–5)"),
                            ("boolean", "Yes / No"),
                            ("text", "Free Text"),
                        ],
                        default="rating",
                        max_length=20,
                    ),
                ),
                ("is_required", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="schedule.feedbackform",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.AddField(
            model_name="feedbackform",
            name="session",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback_form",
                to="schedule.schedulesession",
            ),
        ),
        migrations.CreateModel(
            name="FeedbackAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating_value",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("boolean_value", models.BooleanField(blank=True, null=True)),
                ("text_value", models.TextField(blank=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="schedule.feedbackquestion",
                    ),
                ),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="schedule.feedbackresponse",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SessionBookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reminder_minutes",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (5, "5 min"),
                            (15, "15 min"),
                            (30, "30 min"),
                            (60, "1 hour"),
                        ],
                        default=5,
                    ),
                ),
                ("reminder_sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to="schedule.schedulesession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["session__start_datetime"],
                "unique_together": {("user", "session")},
            },
        ),
    ]
