# Generated by Django 4.2.9 on 2026-08-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedulesession",
            name="notify_all_5_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="schedulesession",
            name="notify_featured_60_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
