# Generated by Django 4.2.9 on 2026-07-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("ceremony", "Ceremony"),
                            ("keynote", "Keynote"),
                            ("workshop", "Workshop"),
                            ("paper", "Paper Session"),
                            ("poster", "Poster Session"),
                            ("break", "Break"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "day",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Conference day (1, 2, 3...)"
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("room", models.CharField(blank=True, max_length=100)),
                ("speaker", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["day", "start_time"],
            },
        ),
    ]
