# Generated by Django 4.2.9 on 2026-08-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pointentry",
            name="action",
            field=models.CharField(
                choices=[
                    ("signup", "Account Created"),
                    ("checkin", "Check-in"),
                    ("meal", "Meal Check-in"),
                    ("poll_vote", "Poll Vote"),
                    ("photo_upload", "Photo Upload"),
                    ("profile_completion", "Profile Completion"),
                    ("feedback", "Session Feedback"),
                    ("networking", "Connection Made"),
                    ("daily_login", "Daily Login Bonus"),
                ],
                max_length=30,
            ),
        ),
    ]
