# Generated by Django 4.2.9 on 2026-07-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConferenceSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="ETD 2026", max_length=200)),
                (
                    "tagline",
                    models.CharField(blank=True, default="IIT Delhi", max_length=300),
                ),
                (
                    "website_url",
                    models.URLField(blank=True, default="https://etd2026.iitd.ac.in"),
                ),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="conference/"),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "venue",
                    models.CharField(
                        blank=True, default="IIT Delhi, New Delhi", max_length=300
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Conference Setting",
            },
        ),
    ]
