# Generated by Django 4.2.9 on 2026-07-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_designation_user_gender_user_research_interests"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="suspended_reason",
            field=models.TextField(
                blank=True, help_text="Reason for account suspension"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="warning_note",
            field=models.TextField(
                blank=True, help_text="Admin warning message sent to user"
            ),
        ),
    ]
