# Generated by Django 4.2.9 on 2026-08-01 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConnectionRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("contact", "Contact Card"),
                            ("speaker", "Speaker Discussion"),
                        ],
                        default="contact",
                        max_length=10,
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("research_collab", "Research Collaboration"),
                            ("session_discuss", "Session Discussion"),
                            ("digital_libraries", "Digital Libraries"),
                            ("metadata", "Metadata"),
                            ("ai", "AI"),
                            ("open_access", "Open Access"),
                            ("networking", "Networking"),
                            ("career", "Career"),
                            ("other", "Other"),
                        ],
                        default="networking",
                        max_length=30,
                    ),
                ),
                ("custom_topic", models.CharField(blank=True, max_length=100)),
                ("message", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("later", "Later"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("research_collab", "Research Collaboration"),
                            ("session_discuss", "Session Discussion"),
                            ("digital_libraries", "Digital Libraries"),
                            ("metadata", "Metadata"),
                            ("ai", "AI"),
                            ("open_access", "Open Access"),
                            ("networking", "Networking"),
                            ("career", "Career"),
                            ("other", "Other"),
                        ],
                        default="networking",
                        max_length=30,
                    ),
                ),
                ("custom_topic", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                (
                    "participant_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations_as_a",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "participant_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations_as_b",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation",
                        to="chat.connectionrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_message_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="chat/images/"),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[("text", "Text"), ("image", "Image")],
                        default="text",
                        max_length=10,
                    ),
                ),
                ("delivered", models.BooleanField(default=True)),
                ("read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.conversation",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
