# Generated by Django 4.2.9 on 2026-07-26 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("checkins", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkin",
            name="goodies_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="checkin",
            name="goodies_confirmed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="goodies_confirmed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="checkin",
            name="goodies_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="checkin",
            name="goodies_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("received", "Received"),
                    ("skipped", "Skipped"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
