# Generated by Django 4.2.9 on 2026-07-29 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Speaker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("prof", "Prof."),
                            ("dr", "Dr."),
                            ("mr", "Mr."),
                            ("ms", "Ms."),
                            ("", "(none)"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("designation", models.CharField(blank=True, max_length=200)),
                ("institute", models.CharField(blank=True, max_length=300)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("bio", models.TextField(blank=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="speakers/photos/"
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("google_scholar_url", models.URLField(blank=True)),
                ("researchgate_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("is_keynote", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_order", "last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="SpeakerTalk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=400)),
                ("abstract", models.TextField(blank=True)),
                ("track", models.CharField(blank=True, max_length=200)),
                ("talk_date", models.DateField(blank=True, null=True)),
                ("talk_time", models.CharField(blank=True, max_length=20)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "speaker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="talks",
                        to="speakers.speaker",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "talk_date", "talk_time"],
            },
        ),
    ]
